### ISSUE TITLE
使用OC升级到10.15.2，USB工作不正常

### ISSUE THREAD

**Issue by hesscn** [RenAmamiya/HP-Zhan-66-Pro-G1#3]
系统中能看USB3.0设备，但是没有正常工作，包括U盘和USB无线网卡

**Comment by heidaren0000** [comment]
哥们我之前看见你用 dw1820a, 但是今天看见你把 repo 删了...请问一下你是怎么驱动的😂 我的插电脑上就死机了

**Comment by hesscn** [comment]
@heidaren0000 死机关闭 1. 先进->系统选项->Configure Storage Controller for Intel Optane
  2. 安全->安全配置->Physical Presence Interface

至于驱动dw1820a，
1. 加入BrcmBluetoothInjector.kext  BrcmFirmwareData.kext BrcmPatchRAM3.kext三个文件
2. DeviceProperties 里改成
```
				<key>AAPL,slot-name</key>
				<string>Internal@0,28,5/0,0</string>
				<key>compatible</key>
				<string>pci14e4,43a3</string>
				<key>device_type</key>
				<string>AirPort Extreme</string>
				<key>model</key>
				<string>Dell Wireless 1820A 802.11ac</string>
				<key>name</key>
				<string>AirPort</string>
				<key>pci-aspm-default</key>
				<integer>0</integer>
```
3. boot-args：-v dart=0 darkwake=0 brcmfx-driver=2 brcmfx-country=#a abm_firstpolldelay=16000 -lilubetaall -applbklbeta -applealcbeta debug=0x100 -cpufbeta -cpufdbg -igfxbeta -disablegfxfirmware bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300

**Comment by heidaren0000** [comment]
牛逼👍谢谢大佬

**Comment by heidaren0000** [comment]
> @heidaren0000 死机关闭 1. 先进->系统选项->Configure Storage Controller for Intel Optane
> 2. 安全->安全配置->Physical Presence Interface
> 
> 至于驱动dw1820a，
> 
> 1. 加入BrcmBluetoothInjector.kext  BrcmFirmwareData.kext BrcmPatchRAM3.kext三个文件
> 2. DeviceProperties 里改成
> 
> ```
> 				<key>AAPL,slot-name</key>
> 				<string>Internal@0,28,5/0,0</string>
> 				<key>compatible</key>
> 				<string>pci14e4,43a3</string>
> 				<key>device_type</key>
> 				<string>AirPort Extreme</string>
> 				<key>model</key>
> 				<string>Dell Wireless 1820A 802.11ac</string>
> 				<key>name</key>
> 				<string>AirPort</string>
> 				<key>pci-aspm-default</key>
> 				<integer>0</integer>
> ```
> 
> 1. boot-args：-v dart=0 darkwake=0 brcmfx-driver=2 brcmfx-country=#a abm_firstpolldelay=16000 -lilubetaall -applbklbeta -applealcbeta debug=0x100 -cpufbeta -cpufdbg -igfxbeta -disablegfxfirmware bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300

大佬，我这里改完了还是死机没响应，您看看还有什么选项跟死机有关的麻烦您看一看，我好尝试一下😂👍

**Comment by heidaren0000** [comment]
我的网卡是联想版的 dw1820a👍

**Comment by hesscn** [comment]
> 我的网卡是联想版的 dw1820a

安全选项里面关闭SGX试试

**Comment by heidaren0000** [comment]
> > 我的网卡是联想版的 dw1820a
> 
> 安全选项里面关闭SGX试试

大佬我这边已经关上了还是死机😂

**Comment by hesscn** [comment]
> > > 我的网卡是联想版的 dw1820a
> > 
> > 
> > 安全选项里面关闭SGX试试
> 
> 大佬我这边已经关上了还是死机

没办法了

**Comment by heidaren0000** [comment]
> > > > 我的网卡是联想版的 dw1820a
> > > 
> > > 
> > > 安全选项里面关闭SGX试试
> > 
> > 
> > 大佬我这边已经关上了还是死机
> 
> 没办法了

好的, 谢谢大佬了👍 我这边打算上原装卡 + sata 固态了😂
