### ISSUE TITLE
switching to OC steps

### ISSUE THREAD

**Issue by 89gnahT** [RenAmamiya/HP-Zhan-66-Pro-G1#4]
Hi, i was using your config but when I check some of your recent commits, you switched to OpenCore bootloader. Can you tell me the steps to do so, or I can just drop in and replace the current boot folder ? I also using dual boot with windows

**Comment by TzeKitKwok** [comment]
Replace and backup current EFI, boot and press F9 to select the file boot entry to find OpenCore.efi. Select the Mac system disk and press 2.
