### ISSUE TITLE
在oc引导菜单界面，不能进入不了win10

### ISSUE THREAD

**Issue by qqilin1213** [RenAmamiya/HP-Zhan-66-Pro-G1#6]
我用你的最新更新的EFI，进入win10出现recovery界面，只能通过F9进入，在进入win10

**Comment by qqilin1213** [comment]
我用0.58版本的照抄了一遍你的conflig，进入不了win10，直接跳转修复

**Comment by TzeKitKwok** [comment]
我添加了启动项，你下载试下
